"""Add proforma_invoices and proforma_invoice_items tables

Revision ID: 9f0b8a705c99
Revises: n9o0p1q2r3s4
Create Date: 2025-12-08 16:01:49.802081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f0b8a705c99'
down_revision: Union[str, None] = 'n9o0p1q2r3s4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proforma_invoices',
    sa.Column('pi_number', sa.String(length=50), nullable=False),
    sa.Column('pi_date', sa.Date(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('client_po_id', sa.Integer(), nullable=True),
    sa.Column('billing_schedule_id', sa.Integer(), nullable=True),
    sa.Column('place_of_supply', sa.String(length=100), nullable=False),
    sa.Column('place_of_supply_code', sa.String(length=2), nullable=False),
    sa.Column('is_igst', sa.Boolean(), nullable=False),
    sa.Column('reverse_charge', sa.Boolean(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cess_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('round_off', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tds_applicable', sa.Boolean(), nullable=False),
    sa.Column('tds_section', sa.String(length=10), nullable=True),
    sa.Column('tds_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tcs_applicable', sa.Boolean(), nullable=False),
    sa.Column('tcs_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tcs_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_after_tds', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'GENERATED', 'CANCELLED', name='pistatus'), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['billing_schedule_id'], ['billing_schedules.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['client_po_id'], ['client_pos.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proforma_invoices_bank_account_id'), 'proforma_invoices', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_proforma_invoices_branch_id'), 'proforma_invoices', ['branch_id'], unique=False)
    op.create_index(op.f('ix_proforma_invoices_id'), 'proforma_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_proforma_invoices_pi_number'), 'proforma_invoices', ['pi_number'], unique=True)
    op.create_table('proforma_invoice_items',
    sa.Column('proforma_invoice_id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('hsn_sac', sa.String(length=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cess_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cess_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proforma_invoice_id'], ['proforma_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proforma_invoice_items_id'), 'proforma_invoice_items', ['id'], unique=False)
    op.drop_constraint(op.f('bank_accounts_branch_id_fkey'), 'bank_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'bank_accounts', 'branches', ['branch_id'], ['id'])
    op.alter_column('billing_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_billing_schedules_client_po_id'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_due_date'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_status'), table_name='billing_schedules')
    op.create_index(op.f('ix_billing_schedules_id'), 'billing_schedules', ['id'], unique=False)
    op.drop_index(op.f('ix_cash_expenses_bank_account_id'), table_name='cash_expenses')
    op.drop_index(op.f('ix_cash_expenses_branch_id'), table_name='cash_expenses')
    op.drop_index(op.f('ix_cash_expenses_expense_category_id'), table_name='cash_expenses')
    op.drop_index(op.f('ix_cash_expenses_financial_year'), table_name='cash_expenses')
    op.drop_index(op.f('ix_cash_expenses_project_id'), table_name='cash_expenses')
    op.create_index(op.f('ix_cash_expenses_id'), 'cash_expenses', ['id'], unique=False)
    op.alter_column('chart_of_accounts', 'account_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('client_po_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_po_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_client_po_items_client_po_id'), table_name='client_po_items')
    op.create_index(op.f('ix_client_po_items_id'), 'client_po_items', ['id'], unique=False)
    op.alter_column('client_pos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_pos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_client_pos_client_id'), table_name='client_pos')
    op.drop_index(op.f('ix_client_pos_received_date'), table_name='client_pos')
    op.drop_index(op.f('ix_client_pos_status'), table_name='client_pos')
    op.create_index(op.f('ix_client_pos_id'), 'client_pos', ['id'], unique=False)
    op.create_index(op.f('ix_expense_categories_id'), 'expense_categories', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_attachments_id'), 'invoice_attachments', ['id'], unique=False)
    op.drop_index(op.f('ix_invoices_billing_schedule_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_po_id'), table_name='invoices')
    op.drop_constraint(op.f('fk_invoices_branch_id'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'branches', ['branch_id'], ['id'])
    op.drop_constraint(op.f('fk_ledger_entries_branch_id'), 'ledger_entries', type_='foreignkey')
    op.create_foreign_key(None, 'ledger_entries', 'branches', ['branch_id'], ['id'])
    op.drop_constraint(op.f('fk_payments_bank_account_id'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('fk_payments_branch_id'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'branches', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'bank_accounts', ['bank_account_id'], ['id'])
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.drop_constraint(op.f('fk_purchase_orders_branch_id'), 'purchase_orders', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_orders', 'branches', ['branch_id'], ['id'])
    op.create_index(op.f('ix_states_id'), 'states', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_states_id'), table_name='states')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_purchase_orders_branch_id'), 'purchase_orders', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_payments_branch_id'), 'payments', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_payments_bank_account_id'), 'payments', 'bank_accounts', ['bank_account_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'ledger_entries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ledger_entries_branch_id'), 'ledger_entries', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoices_branch_id'), 'invoices', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_invoices_client_po_id'), 'invoices', ['client_po_id'], unique=False)
    op.create_index(op.f('ix_invoices_billing_schedule_id'), 'invoices', ['billing_schedule_id'], unique=False)
    op.drop_index(op.f('ix_invoice_attachments_id'), table_name='invoice_attachments')
    op.drop_index(op.f('ix_expense_categories_id'), table_name='expense_categories')
    op.drop_index(op.f('ix_client_pos_id'), table_name='client_pos')
    op.create_index(op.f('ix_client_pos_status'), 'client_pos', ['status'], unique=False)
    op.create_index(op.f('ix_client_pos_received_date'), 'client_pos', ['received_date'], unique=False)
    op.create_index(op.f('ix_client_pos_client_id'), 'client_pos', ['client_id'], unique=False)
    op.alter_column('client_pos', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_pos', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_client_po_items_id'), table_name='client_po_items')
    op.create_index(op.f('ix_client_po_items_client_po_id'), 'client_po_items', ['client_po_id'], unique=False)
    op.alter_column('client_po_items', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_po_items', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chart_of_accounts', 'account_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_cash_expenses_id'), table_name='cash_expenses')
    op.create_index(op.f('ix_cash_expenses_project_id'), 'cash_expenses', ['project_id'], unique=False)
    op.create_index(op.f('ix_cash_expenses_financial_year'), 'cash_expenses', ['financial_year'], unique=False)
    op.create_index(op.f('ix_cash_expenses_expense_category_id'), 'cash_expenses', ['expense_category_id'], unique=False)
    op.create_index(op.f('ix_cash_expenses_branch_id'), 'cash_expenses', ['branch_id'], unique=False)
    op.create_index(op.f('ix_cash_expenses_bank_account_id'), 'cash_expenses', ['bank_account_id'], unique=False)
    op.drop_index(op.f('ix_billing_schedules_id'), table_name='billing_schedules')
    op.create_index(op.f('ix_billing_schedules_status'), 'billing_schedules', ['status'], unique=False)
    op.create_index(op.f('ix_billing_schedules_due_date'), 'billing_schedules', ['due_date'], unique=False)
    op.create_index(op.f('ix_billing_schedules_client_po_id'), 'billing_schedules', ['client_po_id'], unique=False)
    op.alter_column('billing_schedules', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('billing_schedules', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'bank_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('bank_accounts_branch_id_fkey'), 'bank_accounts', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_proforma_invoice_items_id'), table_name='proforma_invoice_items')
    op.drop_table('proforma_invoice_items')
    op.drop_index(op.f('ix_proforma_invoices_pi_number'), table_name='proforma_invoices')
    op.drop_index(op.f('ix_proforma_invoices_id'), table_name='proforma_invoices')
    op.drop_index(op.f('ix_proforma_invoices_branch_id'), table_name='proforma_invoices')
    op.drop_index(op.f('ix_proforma_invoices_bank_account_id'), table_name='proforma_invoices')
    op.drop_table('proforma_invoices')
    # ### end Alembic commands ###
