"""add_item_id_item_name_to_invoice_items

Revision ID: a6cac5aca80d
Revises: f528bea7b9ec
Create Date: 2025-12-09 09:36:53.869731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6cac5aca80d'
down_revision: Union[str, None] = 'f528bea7b9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('item_id', sa.Integer(), nullable=True))
    op.add_column('invoice_items', sa.Column('item_name', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'invoice_items', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_column('invoice_items', 'item_name')
    op.drop_column('invoice_items', 'item_id')
    # ### end Alembic commands ###
