"""add pi_terms and purchase_order_terms to settings

Revision ID: f528bea7b9ec
Revises: f565547a8425
Create Date: 2025-12-08 17:06:14.366655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f528bea7b9ec'
down_revision: Union[str, None] = 'f565547a8425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('pi_terms', sa.Text(), nullable=True))
    op.add_column('company_settings', sa.Column('purchase_order_terms', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_settings', 'purchase_order_terms')
    op.drop_column('company_settings', 'pi_terms')
    # ### end Alembic commands ###
