"""add item_id and item_name to proforma_invoice_items

Revision ID: f565547a8425
Revises: 9f0b8a705c99
Create Date: 2025-12-08 16:21:36.300054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f565547a8425'
down_revision: Union[str, None] = '9f0b8a705c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proforma_invoice_items', sa.Column('item_id', sa.Integer(), nullable=True))
    op.add_column('proforma_invoice_items', sa.Column('item_name', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'proforma_invoice_items', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proforma_invoice_items', type_='foreignkey')
    op.drop_column('proforma_invoice_items', 'item_name')
    op.drop_column('proforma_invoice_items', 'item_id')
    # ### end Alembic commands ###
